#!/usr/bin/env bash
# Displays dns infos
domaininfo () {
	answer_section=$(dig "$1" | grep -A1 'ANSWER SECTION' | tail -n 1)

	sub_domain=$(echo "$answer_section" | awk '{print $1;}' FS=.) 
	record_type=$(echo "$answer_section" | awk '{print $4;}')
	ip_address=$(echo "$answer_section" | awk '{print $5}')

	echo "The subdomain $sub_domain is a $record_type record and points to $ip_address" 
}

if [ $# -eq 1 ]
then
	domaininfo "www.$1" 
	domaininfo "lb-01.$1"
	domaininfo "web-01.$1"
	domaininfo "web-02.$1"
elif [ $# -eq 2 ]
then
	domaininfo "$2.$1"
fi
