#!/usr/bin/env bash
# install Nginx
apt-get -y update
apt-get -y install nginx
sed -i  "s/8080/80/g" /etc/nginx/sites-enabled/default
ufw allow 'Nginx HTTP'
echo Hello World! > /var/www/html/index.html
sudo service nginx start
