#!/usr/bin/env bash
# redirection
sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo Holberton School > /var/www/html/index.nginx-debian.html
sudo sed -i "/^\sserver_name.*/a\ rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default;
sudo service nginx start
