#!/usr/bin/env bash
# redirection
sudo apt -y update
sudo apt -y install nginx
ufw allow 'Nginx HTTP'
echo Hello World! > /var/www/html/index.nginx-debian.html
sudo sed -i "/^\sserver_name.*/a\ rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default;
sudo service nginx start
