#!/usr/bin/env bash
# Config Web-02
sudo apt -y update
sudo apt -y install nginx
sudo chown -R ubuntu:ubuntu /var/www
echo Hello World! > /var/www/html/index.nginx-debian.html
echo ceci n\'est pas une page > /var/www/html/404.html
sudo sed -i '/^\sserver_name.*/a \ rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo sed -i '/^\slocation.*/i \ error_page 404 /404.html;' /etc/nginx/sites-available/default
sudo sed -i '/^\slocation.*/i \ add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
sudo nginx -t
sudo service nginx reload
sudo service nginx start
