#!/usr/bin/env bash
# Config Web-02
sudo apt update
sudo apt install -y nginx
sudo apt install -y sed
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i 's/server_name _;$/server_name _;\n\n\tadd_header X-Served-By $hostname;\n/' /etc/nginx/sites-enabled/default
sudo service nginx restart
