#!/usr/bin/env bash
# loop from 1 to 10
counter=0
while [ $counter -lt 10 ]; do
	(( counter+=1 ))
	if [ $counter -eq 4 ]; then
		echo "bad luck"
	elif [ $counter -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
done
