#!/usr/bin/env bash
# displays hours and minutes
counter=0
while [ $counter -lt 13 ]; do
	echo "Hour: $counter"
	minute=0
	while [ $minute -lt 59 ]; do
		(( minute+=1 ))
		echo "$minute"
	done
	(( counter+=1 ))
done
